name: Build binaries for distribution
on: [workflow_dispatch]

jobs:
  build:
    name: Run Python Tests
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [macos-11, ubuntu-20.04, ubuntu-18.04, ubuntu-16.04, windows-2019, windows-2022]

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt pyinstaller

    - name: Install samtools
      run: |
         wget https://github.com/samtools/samtools/releases/download/1.14/samtools-1.14.tar.bz2
         bunzip2 samtools-1.14.tar.bz2
         tar xvf samtools-1.14.tar
         cd samtools-1.14
         ./configure
         make
         cp samtools ..
         cd ..

    - name: Install readItAndKeep
      run: |
        git clone https://github.com/GenomePathogenAnalysisService/read-it-and-keep.git
        cd read-it-and-keep/src
        make
        mv readItAndKeep ../..
        cd ../..
        rm -r read-it-and-keep

    - name: Test with pytest
      run: |
        pytest --exitfirst --verbose --failed-first \
        --cov=. --cov-report html tests/

    - name: Create pyinstaller single binary
      run: |
        python3 -m PyInstaller -F bin/gpas-upload

    - name: Copy files into dist/
      run: |
        cp gpas_uploader/MN908947_no_polyA.fasta dist/
        cp readItAndKeep dist/
        cp samtools dist/

    - name: Test binary
      run: |
        cd dist/
        ./gpas-upload --json decontaminate ../examples/illumina-bam-upload.csv

    # - name: Store dist
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: gpas-upload-${{ matrix.os }}
    #     path: dist/*
