name: Tests
on: [push]

jobs:
  build:
    name: Run Python Tests
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: UTC

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt

    - name: Install samtools
      run: |
         wget https://github.com/samtools/samtools/releases/download/1.14/samtools-1.14.tar.bz2
         bunzip2 samtools-1.14.tar.bz2
         tar xvf samtools-1.14.tar
         cd samtools-1.14
         ./configure
         make
         sudo make install
         cd ..

    - name: Install readItAndKeep
      run: |
        git clone git@github.com:GenomePathogenAnalysisService/read-it-and-keep.git
        cd read-it-and-keep/src
        make
        mv readItAndKeep ../..
        cd ../..

    - name: Test with pytest
      run: |
        pytest --exitfirst --verbose --failed-first \
        --cov=. --cov-report html
